SELECT * FROM Highscores
ORDER BY score DESC
FETCH NEXT 10 ROWS ONLY;

SELECT * FROM Highscores
ORDER BY score DESC
OFFSET 90 ROWS
FETCH NEXT 10 ROWS ONLY;

SELECT *
  FROM Highscores
  WHERE score < 300
  ORDER BY score DESC
  FETCH FIRST 3 ROWS ONLY;